import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Provider as DataProvider } from "@/context/data_context"
import { Provider as ConnectionProvider } from "@/context/connect"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Leilao Centavos',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-purple-50">
        <ConnectionProvider><DataProvider>{children}</DataProvider></ConnectionProvider>
      </body>
    </html>
  )
}
